#pragma config(Sensor, dgtl1,  EncoderDriveLeft, sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  EncoderDriveRight, sensorQuadEncoder)
#pragma config(Motor,  port2,           DriveLeft,     tmotorVex393, openLoop)
#pragma config(Motor,  port9,           DriveRight,    tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Michael Wallace
//6/15/2015
//MT SAC VEX ROBOTICS Guide to new robotic programers

#include "Robot_Functions.h"// includes drive function right click the name and click open to include to view file

int const DEFAULAT_TIME_OUT_MS = 5000;//5 seconds

//timer t1 is for drive

//function to clear both drive encoders
void clearDriveEncoders();

//function to overload drive function with a time out and encoder distance values
bool drive(short throttle, short steering, int distance, int const DEFAULT_TIME_OUT = DEFAULAT_TIME_OUT_MS);

//main
task main()
{
	int distance_forward = 1000;
	int distance_turn = 500;

	//go forward for distance
	drive(100, 0, distance_forward);
	wait1Msec(1000);
	drive(0, -100, distance_turn);
	wait1Msec(1000);
	drive(100, 0, distance_forward);



}//end main

//function to clear both drive encoders
void clearDriveEncoders()
{
	SensorValue(EncoderDriveLeft) = 0;
	SensorValue(EncoderDriveRight) = 0;
}


//function to drive distance and check if timed out
//returns true if success
//false if failure
bool drive(short throttle, int steering, int distance, int const DEFAULT_TIME_OUT)
{
	ClearTimer(T1);//clear timer to keep track of time to reach distance
	clearDriveEncoders();//clear both encoders
	while(abs(SensorValue(EncoderDriveLeft)) < distance && abs(SensorValue(EncoderDriveRight)) < distance)//make sure both sides have reach the proper distance
	{
		drive(throttle, steering);
		if(time1[T1] > DEFAULT_TIME_OUT)//check if robot has take too long to reach distance
		{
			drive(0,0);//stop drive
			return false;//destiantion failed timed out return false
		}
	}

	drive(0,0);//stop drive
	return true;//distance success return true
}
