#pragma config(Sensor, in1,    PotLift,        sensorPotentiometer)
#pragma config(Sensor, in2,    teamSelection,  sensorPotentiometer)
#pragma config(Sensor, in3,    SharpIR,        sensorAnalog)
#pragma config(Sensor, dgtl1,  EncoderDriveLeft, sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  EncoderDriveRight, sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  ButtonFront,    sensorTouch)
#pragma config(Sensor, dgtl6,  SonarFront,     sensorSONAR_inch)
#pragma config(Motor,  port2,           DriveLeft,     tmotorVex393, openLoop)
#pragma config(Motor,  port5,           Lift,          tmotorVex393, openLoop)
#pragma config(Motor,  port9,           DriveRight,    tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Robot_Functions.h"
#include "InfraredSensor.h"

//for GP2Y0A41SK0F 4cm to 30cm
int const DISTANCE = 15;//cm
int const SPEED_FORWARD = 60;

//IR function will not be used because IR is not a common vex component

task main()
{

		//might not work by using sensor port as argument change function if fails to work
		int distanceValue = IRValuePower(SharpIR);

		//does not check for dead zone in fron of IR distance sensor
		while(distanceValue > DISTANCE)//while IR distance sensor is greater than desired value
		{
			drive(SPEED_FORWARD, 0);//drive forward untill below desired range
			distanceValue = IRValuePower(SharpIR);
		}

		drive(0,0);//stop drive
}
