#pragma config(Sensor, in1,    PotLift,        sensorPotentiometer)
#pragma config(Sensor, in2,    teamSelection,  sensorPotentiometer)
#pragma config(Sensor, in3,    SharpIR,        sensorAnalog)
#pragma config(Sensor, dgtl1,  EncoderDriveLeft, sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  EncoderDriveRight, sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  ButtonFront,    sensorTouch)
#pragma config(Sensor, dgtl6,  SonarFront,     sensorSONAR_inch)
#pragma config(Motor,  port2,           DriveLeft,     tmotorVex393, openLoop)
#pragma config(Motor,  port5,           Lift,          tmotorVex393, openLoop)
#pragma config(Motor,  port9,           DriveRight,    tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
/*
Michael Wallace
6/15/2015
MT SAC VEX ROBOTICS Guide to new robotic programmers

Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
*/
#include "Robot_Functions.h"
#include "InfraredSensor.h"

//for GP2Y0A41SK0F 4cm to 30cm
int const DISTANCE = 15;//cm
int const SPEED_FORWARD = 60;

//IR function will not be used because IR is not a common vex component

task main()
{

		//might not work by using sensor port as argument change function if fails to work
		int distanceValue = IRValuePower(SharpIR);

		//does not check for dead zone in fron of IR distance sensor
		while(distanceValue > DISTANCE)//while IR distance sensor is greater than desired value
		{
			drive(SPEED_FORWARD, 0);//drive forward untill below desired range
			distanceValue = IRValuePower(SharpIR);
		}

		drive(0,0);//stop drive
}
