#pragma config(Motor,  port2,           DriveLeft,     tmotorVex393, openLoop)
#pragma config(Motor,  port9,           DriveRight,    tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Michael Wallace
6/15/2015
MT SAC VEX ROBOTICS Guide to new robotic programmers

Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
*/

#include "Robot_Functions.h"// includes drive function right click the name and click open to include to view file

task main()
{
	//drive forward for five seconds and stop
	ClearTimer(T1);// clears timer 1
	while(time1[T1] < 5000)//loop while timer 1 is less the 5000 ms
	{
		drive(100,0); //set drive motors to forward at 100
	}//end while loop
	drive(0,0);//set all drive motors to zero

	//turn left for two seconds and stop
	ClearTimer(T1);// clears timer 1
	while(time1[T1] < 2000)//loop while timer 1 is less the 5000 ms
	{
		drive(0,-60);//set drive motors to forward at 100
	}//end while loop
	drive(0,0);//set all drive motors to zero

	//drive forward for five seconds and stop
	ClearTimer(T1);// clears timer 1
	while(time1[T1] < 5000)//loop while timer 1 is less the 5000 ms
	{
		drive(100,0);	//set drive motors to forward at 100
	}//end while loop
	drive(0,0);//set all drive motors to zero
     
    //another way to achieve the same behavior is to use the wait function
    drive(100,0);//set drive motors to forward at 100
    wait1Msec(1000);//do nothing for 1000 ms
    drive(0,0);//turn all drive motors off

}//end main
