#pragma config(Motor,  port2,           DriveLeft,     tmotorVex393, openLoop)
#pragma config(Motor,  port9,           DriveRight,    tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Michael Wallace
//6/15/2015
//MT SAC VEX ROBOTICS Guide to new robotic programers

#include "Robot_Functions.h"// includes drive function right click the name and click open to include to view file

task main()
{
	//drive forward for five seconds and stop
	ClearTimer(T1);// clears timer 1
	while(time1[T1] < 5000)//loop while timer 1 is less the 5000 ms
	{
		drive(100,0); //set drive motors to forward at 100
	}//end while loop
	drive(0,0);//set all drive motors to zero

	//turn left for two seconds and stop
	ClearTimer(T1);// clears timer 1
	while(time1[T1] < 2000)//loop while timer 1 is less the 5000 ms
	{
		drive(0,-60);//set drive motors to forward at 100
	}//end while loop
	drive(0,0);//set all drive motors to zero

	//drive forward for five seconds and stop
	ClearTimer(T1);// clears timer 1
	while(time1[T1] < 5000)//loop while timer 1 is less the 5000 ms
	{
		drive(100,0);	//set drive motors to forward at 100
	}//end while loop
	drive(0,0);//set all drive motors to zero

}//end main
