#pragma config(Sensor, in1,    PotLift,        sensorPotentiometer)
#pragma config(Sensor, in2,    teamSelection,  sensorPotentiometer)
#pragma config(Sensor, dgtl1,  EncoderDriveLeft, sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  EncoderDriveRight, sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  ButtonFront,    sensorTouch)
#pragma config(Motor,  port2,           DriveLeft,     tmotorVex393, openLoop)
#pragma config(Motor,  port5,           Lift,          tmotorVex393, openLoop)
#pragma config(Motor,  port9,           DriveRight,    tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Robot_Functions.h"

int const DISTANCE_REVERSE_TURN = 1000;
int const SPEED_REVERSE_TURN = 40;
int const SPEED_FORWARD = 60;


task main()
{
	while(true)//infinte loop
	{
		while(SensorValue(ButtonFront) == 0)//while button is not pressed
		{
			drive(SPEED_FORWARD, 0);//drive forward until robot hits some thing
		}
		drive(0,0);//stop drive


		wait1Msec(500);//WAIT

		byte direction = random(1);//random direction 0 or 1

		if(direction == 1)//go backwards and turn to the left
		{
			drive(-SPEED_REVERSE_TURN, SPEED_REVERSE_TURN/2, DISTANCE_REVERSE_TURN);
		}
		else//go backwards and turn to the right
		{
			drive(-SPEED_REVERSE_TURN, -SPEED_REVERSE_TURN/2, DISTANCE_REVERSE_TURN);
		}

		wait1Msec(500);//WAIT

	}
}
