#pragma config(Sensor, in1,    PotLift,        sensorPotentiometer)
#pragma config(Sensor, in2,    teamSelection,  sensorPotentiometer)
#pragma config(Sensor, dgtl1,  EncoderDriveLeft, sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  EncoderDriveRight, sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  ButtonFront,    sensorTouch)
#pragma config(Sensor, dgtl6,  SonarFront,     sensorSONAR_inch)
#pragma config(Motor,  port2,           DriveLeft,     tmotorVex393, openLoop)
#pragma config(Motor,  port5,           Lift,          tmotorVex393, openLoop)
#pragma config(Motor,  port9,           DriveRight,    tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
/*
Michael Wallace
6/15/2015
MT SAC VEX ROBOTICS Guide to new robotic programmers

Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
*/
#include "Robot_Functions.h"

int const DISTANCE = 20;//inches
int const SPEED_FORWARD = 60;

bool driveSonar(short throttle, short steering, int distance, int const DEFAULT_TIME_OUT = DEFAULAT_TIME_OUT_MS);


task main()
{
	driveSonar(SPEED_FORWARD, 0, DISTANCE);
}


/************************************************/
//function to drive until sonar is below distance
/************************************************/
bool driveSonar(short throttle, int steering, int distance, int const DEFAULT_TIME_OUT)
{
		int value = SensorValue(SonarFront);
		ClearTimer(T1);//clear timer to keep track of time to reach distance
		while(value > 0 && value > distance)//while SONAR is valid (>0) and greater desired distance
		{
			drive(throttle, 0);//drive forward while sonar is valid and until less than some distance
			value = SensorValue(SonarFront);
			if(value < 0 || time1[T1] > DEFAULT_TIME_OUT)//check if robot has taken too long to reach distance
			{
				drive(0,0);//stop drive
				return false;//destiantion failed timed out return false
			}
		}
		drive(0,0);//stop drive
		return true;
}
