#pragma config(Sensor, in1,    PotLift,        sensorPotentiometer)
#pragma config(Sensor, in2,    teamSelection,  sensorPotentiometer)
#pragma config(Sensor, dgtl1,  EncoderDriveLeft, sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  EncoderDriveRight, sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  ButtonFront,    sensorTouch)
#pragma config(Motor,  port2,           DriveLeft,     tmotorVex393, openLoop)
#pragma config(Motor,  port5,           Lift,          tmotorVex393, openLoop)
#pragma config(Motor,  port9,           DriveRight,    tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
/*
Michael Wallace
6/15/2015
MT SAC VEX ROBOTICS Guide to new robotic programmers

Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
*/
#include "Robot_Functions.h"

int const DISTANCE_REVERSE_TURN = 1000;
int const SPEED_REVERSE_TURN = 40;
int const SPEED_FORWARD = 60;


task main()
{
	while(true)//infinte loop
	{
		while(SensorValue(ButtonFront) == 0)//while button is not pressed
		{
			drive(SPEED_FORWARD, 0);//drive forward until robot hits some thing
		}
		drive(0,0);//stop drive


		wait1Msec(500);//WAIT

		byte direction = random(1);//random direction 0 or 1

		if(direction == 1)//go backwards and turn to the left
		{
			drive(-SPEED_REVERSE_TURN, SPEED_REVERSE_TURN/2, DISTANCE_REVERSE_TURN);
		}
		else//go backwards and turn to the right
		{
			drive(-SPEED_REVERSE_TURN, -SPEED_REVERSE_TURN/2, DISTANCE_REVERSE_TURN);
		}

		wait1Msec(500);//WAIT

	}
}
